# Generated by Django 2.2.28 on 2022-06-14 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goodscategorybrand_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='goods_number',
            new_name='goods_num',
        ),
    ]
