# Generated by Django 2.2.28 on 2022-06-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20220614_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='store_price',
            new_name='shop_price',
        ),
    ]
